[Interface]
PrivateKey = <client_private_key>
Address = 10.10.10.2/24

[Peer]
PublicKey = vvOfQ1bYvP5KuGTEvW+xL4wn2fmomwSLg2jp3Z4liDw=
Endpoint = 10.0.0.1:51820
AllowedIPs = 10.10.10.0/24, 192.168.1.0/24
